#!/usr/bin/env bash

set -e
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# I do unique things to my machines depending on which one..
# EG:
#  - the desktop PC has iommu VFIO passthrough for GameOS (windows)
#  - the laptop(s) have things like TLP, bumblebee or whatnot
# I'm simply going to use the "model name" of the CPU from /proc/cpuinfo
# if there is a directory here called ./tweaks/<model name> (spaces replaced with underscores)
# then this script will execute the scripts in there in sequence


CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"

cd "${ROOTDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${ROOTDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${ROOTDIR}"/home -c "${CONFIG}" "${@}"
