#!/usr/bin/env bash

set -e
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

set -x
cd "${ROOTDIR}"

# This will download the dotbot script into the (submodule) dir "./dotbot"
git submodule update --init --recursive

# Instruct dotbot to start ensuring symlinks + shell scripts are executed
./dotbot/bin/dotbot -d home -c dotbot.yaml "${@}"

cd tweaks
./all.sh
