#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

/usr/bin/dunst &

# gnome-session --session=i3 &
export $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

# lock screen @ 15min
xautolock -time 15 -locker "$HOME/.config/i3/scripts/i3exit lock" &

# suspend @ 25min
xautolock -time 25 -locker "$HOME/.config/i3/scripts/i3exit suspend" &

# $HOME/.bin/screen-auto.sh
LOG="$HOME/.xlog"
cp /dev/null "$LOG"
i3 > "$LOG" 2>>"$LOG"
