#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi



# dbus-update-activation-environment --systemd DISPLAY

/usr/bin/dunst &

# /usr/bin/dunst \
#   -fn "Hack 20" \
#   -geometry +0+35 \
#   -lf "#ffffff" \
#   -lb "#888888" \

#   -cf "#ffffff" \
#   -cb "#900000" \

#   -nf "#ffffff" \
#   -nb "#00b08a" \
#   -sep_height 2 \
#   -format "%a: [%s] %b %p" \
#   -follow keyboard \
#   -history_length 5 \
#   -key ctrl+space \
#   -alignment center \
#   -icon_position off \
#   -padding 1 \
#   -horizontal_padding 1 \
#   -sep_color 000000 \
#   -indicate_hidden \
#   -word_wrap \
#   -hide_duplicates_count \
#   -show_indicators &



optirun gnome-session --session=i3 &
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

xautolock -time 25 -locker "$HOME/.config/i3/scripts/i3exit suspend" &

$HOME/.bin/screen-auto.sh
i3
